spring.application.name=perfumeEcommerceApp


spring.datasource.url=${DB_NAME}
spring.datasource.username=blezant
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=true
server.port=8080
spring.jpa.hibernate.ddl-auto=update
api.secret.key=${API_KEY}

#Resend properties

resend_mail=${RESEND_MAIL}
resend.api.key=${RESEND_API_KEY}


#smtp not in use anymore *******************
#spring.mail.host=smtp.gmail.com
#spring.mail.port=${MAIL_PORT}
#spring.mail.username=${MAIL}
#spring.mail.password=${MAIL_PASSWORD}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#this rabbit mq properties configuration not in use anymore *******************
#spring.rabbitmq.host=amqps://nrsdztyu:xi75nqnc_v4FSe6vziZk0TOkicaCPnfg@dog.lmq.cloudamqp.com/nrsdztyu
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=nrsdztyu
#spring.rabbitmq.password=xi75nqnc_v4FSe6vziZk0TOkicaCPnfg

spring.rabbitmq.addresses=amqps://nrsdztyu:xi75nqnc_v4FSe6vziZk0TOkicaCPnfg@dog.lmq.cloudamqp.com/nrsdztyu



